# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa6de360898e515f21254fdbf89c662a559dae6ea533e11129dbd29cd25148e79f77c2d44767e36efb9e2a89d80861e9eea33cf67ee2e53aac242d031a7885c6

test:
  secret_key_base: 128337b7655c8dee2977d7b2068fb40b16a78f2406851c879ac416ca1f21a35b538aecf7d298fafb7846c3b4ca6b135733e936901312c54d41adfbca88e036d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
